import XCTest

/// Pins the static launch screen declared in `Info.plist`'s `UILaunchScreen` dictionary.
///
/// iOS shows this screen before any app code runs — before Compose, before even the Kotlin
/// framework is loaded — built entirely from plist keys, not code. Today `UILaunchScreen` is `{}`:
/// present only because an *absent* key runs the app letterboxed in a small compatibility window,
/// but an *empty* one carries no artwork, so the launch screen is just the Hearth-canvas-less
/// system default. This cycle pins the three keys that put the Hearth canvas colour and the launch
/// tile from cycles 1 and 2 onto it:
///
///  - `UIColorName` = `"HearthCanvas"` — the colour set `HearthColorAssetTests` already proved
///    resolves in both appearances.
///  - `UIImageName` = `"HearthLaunchTile"` — the image set `HearthLaunchTileTests` already proved
///    resolves and is coloured correctly in both appearances.
///  - `UIImageRespectsSafeAreaInsets` = `true` — without it the tile is allowed to sit under the
///    notch/Dynamic Island rather than being inset from it.
///
/// `Info.plist` is generated by XcodeGen from `project.yml`'s `targets.HouseholdHub.info.properties`
/// (see that file's own comment on why `GENERATE_INFOPLIST_FILE` was rejected in favour of this).
/// `Bundle.main.infoDictionary` is how a running app reads its own already-merged plist — the same
/// mechanism `UIApplication` itself uses to decide what to show before `application(_:didFinishLaunchingWithOptions:)`
/// even runs — so asserting through it, rather than parsing the plist file, tests exactly what iOS sees.
///
/// Three separate test methods rather than one, so a wrong value at one key does not hide a wrong
/// value at another: with `UILaunchScreen` still `{}`, all three keys are absent, and each lookup
/// must produce a *distinct* `XCTAssertEqual` failure (`nil` vs `Optional("...")`) — not a single
/// `XCTUnwrap` failure the way cycles 1 and 2 failed, because the dictionary itself is present
/// (just empty), so there is nothing to unwrap-fail on.
final class LaunchScreenPlistTests: XCTestCase {

    func testLaunchScreenColorNameIsHearthCanvas() throws {
        let launchScreen = try launchScreenDictionary()

        XCTAssertEqual(launchScreen["UIColorName"] as? String, "HearthCanvas")
    }

    func testLaunchScreenImageNameIsHearthLaunchTile() throws {
        let launchScreen = try launchScreenDictionary()

        XCTAssertEqual(launchScreen["UIImageName"] as? String, "HearthLaunchTile")
    }

    func testLaunchScreenImageRespectsSafeAreaInsets() throws {
        let launchScreen = try launchScreenDictionary()

        XCTAssertEqual(launchScreen["UIImageRespectsSafeAreaInsets"] as? Bool, true)
    }

    /// The plist naming an asset is only half the contract: if the name were misspelled, or the
    /// asset it points at were ever renamed or removed, `UILaunchScreen` would still be
    /// well-formed and these three tests above would still pass, while the *actual* launch screen
    /// silently went blank — exactly the failure mode this cycle exists to catch. `HearthCanvas`
    /// and `HearthLaunchTile` already have dedicated resolution/appearance tests of their own
    /// (`HearthColorAssetTests`, `HearthLaunchTileTests`), so this does not re-check their colours;
    /// it only checks that the *specific strings this plist carries* are names something in the
    /// catalog actually answers to — the missing link between "the plist says X" and "X exists".
    func testLaunchScreenNamesResolveToRealAssets() throws {
        let launchScreen = try launchScreenDictionary()

        let colorName = try XCTUnwrap(
            launchScreen["UIColorName"] as? String,
            "UILaunchScreen.UIColorName is missing or not a string; cannot check it resolves."
        )
        let imageName = try XCTUnwrap(
            launchScreen["UIImageName"] as? String,
            "UILaunchScreen.UIImageName is missing or not a string; cannot check it resolves."
        )

        XCTAssertNotNil(
            UIColor(named: colorName),
            "UILaunchScreen.UIColorName names \"\(colorName)\", but no such color set resolves "
                + "from the app bundle's asset catalog."
        )
        XCTAssertNotNil(
            UIImage(named: imageName),
            "UILaunchScreen.UIImageName names \"\(imageName)\", but no such image set resolves "
                + "from the app bundle's asset catalog."
        )
    }

    // MARK: - Helpers

    /// Unwraps `UILaunchScreen` from the main bundle's merged Info.plist once, with a message
    /// naming exactly where it comes from — `project.yml`'s `info.properties.UILaunchScreen`,
    /// generated into `HouseholdHub/Info.plist` — so a `nil` here (the key removed entirely,
    /// rather than left empty) is still legible.
    private func launchScreenDictionary(
        file: StaticString = #filePath, line: UInt = #line
    ) throws -> [String: Any] {
        try XCTUnwrap(
            Bundle.main.infoDictionary?["UILaunchScreen"] as? [String: Any],
            "Info.plist has no UILaunchScreen dictionary — check "
                + "project.yml's targets.HouseholdHub.info.properties.UILaunchScreen.",
            file: file, line: line
        )
    }
}
