const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT_DIR = path.resolve(__dirname, '..');
const WORKFLOW_PATH = path.join(ROOT_DIR, '.github/workflows/household-hub-backend.yml');
const BACKEND = 'apps/household-hub/backend';

// Missing files read as empty so each check fails with its own message. CRLF checkouts are normalised.
const read = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : '');

// Text of a top-level YAML key's block, up to the next top-level key.
const topLevelBlock = (content, key) => {
  const match = content.match(new RegExp(`^${key}:[^\\n]*\\n((?:[ \\t]+[^\\n]*\\n|[ \\t]*\\n)*)`, 'm'));
  return match ? match[1] : '';
};

test('Household Hub backend CI workflow', async (t) => {
  const workflow = read(WORKFLOW_PATH);

  await t.test('exists', () => {
    assert.ok(fs.existsSync(WORKFLOW_PATH), '.github/workflows/household-hub-backend.yml must exist');
  });

  await t.test('runs on PRs and pushes to master that touch the backend or this workflow', () => {
    const on = topLevelBlock(workflow, 'on');
    for (const event of ['push', 'pull_request']) {
      const block = on.match(new RegExp(`^  ${event}:\\n((?:    [^\\n]*\\n)*)`, 'm'));
      assert.ok(block, `must run on ${event}`);
      assert.match(block[1], /branches: \[master\]/);
      assert.ok(block[1].includes(`- ${BACKEND}/**`), `${event} must watch the backend`);
      assert.ok(block[1].includes('- .github/workflows/household-hub-backend.yml'), `${event} must watch this workflow`);
    }
    // A Renovate PR is merged only once this has run and passed.
    assert.match(topLevelBlock(workflow, 'permissions'), /^  contents: read$/m);
  });

  await t.test('tests on the Python the image runs, read from the Dockerfile', () => {
    // One source of truth: a bump of the base image moves CI with it.
    assert.match(workflow, /sed -n 's\/\^FROM python:\\\(\.\*\\\)-slim\$\/\\1\/p' Dockerfile/);
    assert.match(workflow, /python-version: \$\{\{ steps\.python\.outputs\.version \}\}/);
    assert.match(workflow, /pip install -r requirements-dev\.txt/);
    assert.match(workflow, /python -m pytest tests/);
    assert.match(workflow, new RegExp(`working-directory: ${BACKEND}`));
  });

  await t.test('fails when a lock file no longer matches its .in file', () => {
    // Someone edits requirements.in and forgets to regenerate: the image would install the old set.
    const header = (file) => read(path.join(ROOT_DIR, BACKEND, file)).split('\n')[1].replace(/^#\s*/, '').trim();
    for (const file of ['requirements.txt', 'requirements-dev.txt']) {
      assert.match(header(file), /^uv pip compile /, `${file} must be generated by uv`);
      assert.ok(workflow.includes(header(file)), `the workflow must rerun: ${header(file)}`);
    }
    assert.match(workflow, /pip install uv==\d+\.\d+\.\d+/, 'uv is pinned, so the check does not change under us');
    assert.match(workflow, /git diff --exit-code -- requirements\.txt requirements-dev\.txt/);
  });

  await t.test('builds the image too, so a base image or dependency bump that breaks it fails here', () => {
    assert.match(workflow, /docker build [^\n]*apps\/household-hub\/backend/);
  });

  await t.test('pins every third-party action to a full commit SHA', () => {
    const refs = [...workflow.matchAll(/^\s*(?:-\s*)?uses:\s*["']?([^\s"'#]+)/gm)].map((m) => m[1]);
    assert.ok(refs.length >= 2, 'checkout and setup-python');
    for (const ref of refs) {
      assert.match(ref, /@[0-9a-f]{40}$/, `"${ref}" must be pinned to a 40-character commit SHA`);
    }
  });
});
