"""
The image installs from a lock file: every package, the indirect ones too, at an exact version.
So a rebuild installs what was tested.

  requirements.in        the packages the hub names itself
  requirements.txt       the lock generated from it (what the image installs)
  requirements-dev.in    the test tools, on top of the hub's packages
  requirements-dev.txt   the lock for running the tests

The locks are generated, never edited by hand: see the header of each one for the command.
"""
import re
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
# A marker may follow: the lock is universal, and some packages are for one platform only.
PINNED = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*==[0-9][A-Za-z0-9.+!-]*( ; .+)?$")
TEST_TOOLS = {"pytest", "pytest-asyncio", "pytest-cov"}


def _lines(name: str) -> list[str]:
    path = BACKEND_ROOT / name
    assert path.exists(), f"{name} must exist"
    lines = [line.split("#", 1)[0].strip() for line in path.read_text(encoding="utf-8").splitlines()]
    return [line for line in lines if line]


def _package(line: str) -> str:
    name = re.split(r"[\[<>=!~;\s]", line, maxsplit=1)[0]
    return re.sub(r"[-_.]+", "-", name).lower()


def _packages(name: str) -> set[str]:
    return {_package(line) for line in _lines(name) if not line.startswith("-")}


def _header(name: str) -> str:
    return "\n".join((BACKEND_ROOT / name).read_text(encoding="utf-8").splitlines()[:3])


def test_the_hub_names_its_own_packages_without_the_test_tools():
    direct = _packages("requirements.in")
    assert {"fastapi", "sqlalchemy", "httpx"} <= direct
    assert not direct & TEST_TOOLS


def test_the_lock_is_generated_from_the_hubs_packages_for_the_images_python_on_any_platform():
    header = _header("requirements.txt")
    assert "autogenerated by uv" in header
    assert "uv pip compile requirements.in" in header
    assert "--python-version 3.12" in header
    # Universal: the image is Linux, the tests also run in a venv on Windows.
    assert "--universal" in header


def test_the_lock_pins_every_package_exactly():
    for line in _lines("requirements.txt"):
        assert PINNED.match(line), f"{line!r} must be pinned with =="


def test_the_lock_covers_the_indirect_packages_too():
    direct = _packages("requirements.in")
    locked = _packages("requirements.txt")
    assert direct <= locked, f"missing from the lock: {sorted(direct - locked)}"
    # FastAPI brings Starlette, httpx brings anyio: nobody names them, and they are pinned all the same.
    assert {"starlette", "anyio"} <= locked
    # uvloop cannot be built on Windows; without its marker the local venv would not install.
    uvloop = next(line for line in _lines("requirements.txt") if line.startswith("uvloop=="))
    assert "sys_platform" in uvloop
    assert len(locked) > len(direct)


def test_the_image_leaves_out_the_test_tools():
    assert not _packages("requirements.txt") & TEST_TOOLS


def test_the_dev_lock_is_the_image_lock_plus_the_test_tools():
    assert "-r requirements.in" in _lines("requirements-dev.in")
    assert _packages("requirements-dev.in") == TEST_TOOLS
    assert "uv pip compile requirements-dev.in" in _header("requirements-dev.txt")
    dev = set(_lines("requirements-dev.txt"))
    for line in dev:
        assert PINNED.match(line), f"{line!r} must be pinned with =="
    # The same versions the image runs, or the tests would vouch for something else.
    assert set(_lines("requirements.txt")) <= dev
    assert TEST_TOOLS <= _packages("requirements-dev.txt")


def test_the_image_installs_the_lock_on_a_pinned_python():
    dockerfile = (BACKEND_ROOT / "Dockerfile").read_text(encoding="utf-8").splitlines()
    assert re.fullmatch(r"FROM python:3\.12\.\d+-slim", dockerfile[0]), dockerfile[0]
    assert "RUN pip install --no-cache-dir -r requirements.txt" in [line.strip() for line in dockerfile]
