"""index chat_messages by session and time

Revision ID: 180c460dc76b
Revises: efd5e0befdb0
Create Date: 2026-09-22 15:16:30.758318
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '180c460dc76b'
down_revision: Union[str, None] = 'efd5e0befdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_created')

    # ### end Alembic commands ###
