"""baseline schema

Revision ID: efd5e0befdb0
Revises: 
Create Date: 2026-09-22 15:09:29.538901
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efd5e0befdb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('avatar_color', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_personalities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_alias', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('tool_permissions', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_personalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_personalities_slug'), ['slug'], unique=True)

    op.create_table('calendar_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('calendar_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_credentials_user_id'), ['user_id'], unique=True)

    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('invited_name', sa.String(length=128), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)

    op.create_table('pin_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_resets_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pin_resets_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('app_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_documents_space_id'), ['space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_documents_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_documents_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_personalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_personalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memories_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memories_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memories_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memories_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gossip_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_user_id', sa.String(length=36), nullable=False),
    sa.Column('source_username', sa.String(length=64), nullable=False),
    sa.Column('reporting_agent_id', sa.String(length=36), nullable=True),
    sa.Column('reporting_agent_name', sa.String(length=128), nullable=False),
    sa.Column('target_scope', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporting_agent_id'], ['agent_personalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gossip_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gossip_milestones_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_gossip_milestones_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gossip_milestones_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_gossip_milestones_reporting_agent_id'), ['reporting_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gossip_milestones_source_user_id'), ['source_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gossip_milestones_target_scope'), ['target_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gossip_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_target_scope'))
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_source_user_id'))
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_reporting_agent_id'))
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_is_active'))
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_expires_at'))
        batch_op.drop_index(batch_op.f('ix_gossip_milestones_category'))

    op.drop_table('gossip_milestones')
    op.drop_table('chat_messages')
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_memories_scope'))
        batch_op.drop_index(batch_op.f('ix_agent_memories_category'))
        batch_op.drop_index(batch_op.f('ix_agent_memories_agent_id'))

    op.drop_table('agent_memories')
    op.drop_table('conversation_sessions')
    with op.batch_alter_table('app_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_documents_title'))
        batch_op.drop_index(batch_op.f('ix_app_documents_space_id'))

    op.drop_table('app_documents')
    op.drop_table('spaces')
    with op.batch_alter_table('pin_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_resets_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_pin_resets_code'))

    op.drop_table('pin_resets')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    with op.batch_alter_table('calendar_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_credentials_user_id'))

    op.drop_table('calendar_credentials')
    with op.batch_alter_table('agent_personalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_personalities_slug'))

    op.drop_table('agent_personalities')
    op.drop_table('users')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
